name: GutselCraft
version: '1.0.0'
main: de.gutselcraft.gutselCraft.GutselCraft
api-version: '1.21'
authors: [ Leonard Mueller ]
description: Server Plugin for GutselCraft.de Minecraft Server
website: https://gutselcraft.de
