name: GutselCraft
version: '1.0.0'
main: de.gutselcraft.gutselCraft.GutselCraft
api-version: '1.21'
authors: [ Syntaxx ]
description: Server Plugin for GutselCraft.de Minecraft Server
website: https://gutselcraft.de

commands:
  ping:
    description: Shows your current ping to the server
    usage: /<command>
  antidespawn:
    description: Manage anti-despawn settings for death-dropped items
    usage: /<command> [toggle|settime]
    permission: gutselcraft.antidespawn
    aliases: [ad, nodespawn]
  gutselcraft:
    description: Reload the plugin configuration
    usage: /<command> reload
    aliases: [gc]
  dynamicslots:
    description: Toggle dynamic max player slots
    usage: /<command>
    permission: gutselcraft.dynamicslots
    aliases: [slots, ds]
  mitmachen:
    description: Stimme ab um die Nacht zu überspringen
    usage: /<command>

permissions:
  gutselcraft.antidespawn:
    description: Allows management of anti-despawn settings
    default: op
  gutselcraft.dynamicslots:
    description: Allows toggling dynamic slots feature
    default: op
